version: '3.1'

services:

#  запускаем два приложения

#  1. Postgre SQL
  db:
#    имя пользователя
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: todo_app_db
    ports:
    - 5433:5432

#  2. админка. клиент для РБД
  adminer:
    image: adminer
    restart: always
    ports:
    - 8083:8080