#переменные окружения PORT, JDBC_DATABASE_URL etc нам поставляет сервис хостинга
#указывать конкретный порт для запуска в облаке мы не можем
server:
  servlet:
    context-path: /
  port: ${PORT:8082}

spring:
  datasource:
    #однако помним, что стандартный порт постгреса 5432
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/todo_app_db}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:example}
  jpa:
    properties:
      hibernate:
        jdbc:
          lab:
            #устраняет проблемы связки Spring с Postrgre SQL
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: update
